# my-custom-action/action.yml
name: 'My Custom Action'
description: 'An action that runs a Dockerfile and a Bash script with an argument'
inputs:
  arg:
    description: 'Argument to pass to the Bash script'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arg }}
